<?php

return [
    "valid_ids" => [
        "UMID" => "e-Card/UMID",
        "OFFICE_ID" => "Employee's ID/Office ID",
        "DRIVER_LICENSE" => "Driver's License",
        "PRC" => "Professional Regulation Commission (PRC) ID",
        "PASSPORT" => "Passport",
        "SENIOR_CITIZEN_ID" => "Senior Citizen ID",
        "SSS_ID" => "SSS ID",
        "COMELEC" => "COMELEC / Voter’s ID / COMELEC Registration Form",
        "PHIL_ID" => "Philippine Identification (PhilID / ePhilID)",
        "NBI_CLEARANCE" => "NBI Clearance",
        "IBP" => "Integrated Bar of the Philippines (IBP) ID",
        "FIREARMS_LICENSE" => "Firearms License",
        "AFPSLAI_ID" => "AFPSLAI ID",
        "PVAO_ID" => "PVAO ID",
        "AFP_ID" => "AFP Beneficiary ID",
        "TIN" => "BIR (TIN)",
        "PAGIBIG_ID" => "Pag-ibig ID",
        "PWD" => "Person’s With Disability (PWD) ID",
        "SOLO_PARENT" => "Solo Parent ID",
        "4PS" => "Pantawid Pamilya Pilipino Program (4Ps) ID",
        "BRGY_ID" => "Barangay ID",
        "POSTAL_ID" => "Philippine Postal ID",
        "PHIL_HEALTH_ID" => "Phil-health ID",
        "SCHOOL_ID" => "School ID"
    ],
    "nationality" => [
        "filipino",
        "afghan",
        "albanian",
        "algerian",
        "american",
        "andorran",
        "angolan",
        "antiguans",
        "argentinean",
        "armenian",
        "australian",
        "austrian",
        "azerbaijani",
        "bahamian",
        "bahraini",
        "bangladeshi",
        "barbadian",
        "barbudans",
        "batswana",
        "belarusian",
        "belgian",
        "belizean",
        "beninese",
        "bhutanese",
        "bolivian",
        "bosnian",
        "brazilian",
        "british",
        "bruneian",
        "bulgarian",
        "burkinabe",
        "burmese",
        "burundian",
        "cambodian",
        "cameroonian",
        "canadian",
        "cape verdean",
        "central african",
        "chadian",
        "chilean",
        "chinese",
        "colombian",
        "comoran",
        "congolese",
        "costa rican",
        "croatian",
        "cuban",
        "cypriot",
        "czech",
        "danish",
        "djibouti",
        "dominican",
        "dutch",
        "east timorese",
        "ecuadorean",
        "egyptian",
        "emirian",
        "equatorial guinean",
        "eritrean",
        "estonian",
        "ethiopian",
        "fijian",
        "finnish",
        "french",
        "gabonese",
        "gambian",
        "georgian",
        "german",
        "ghanaian",
        "greek",
        "grenadian",
        "guatemalan",
        "guinea-bissauan",
        "guinean",
        "guyanese",
        "haitian",
        "herzegovinian",
        "honduran",
        "hungarian",
        "i-kiribati",
        "icelander",
        "indian",
        "indonesian",
        "iranian",
        "iraqi",
        "irish",
        "israeli",
        "italian",
        "ivorian",
        "jamaican",
        "japanese",
        "jordanian",
        "kazakhstani",
        "kenyan",
        "kittian and nevisian",
        "kuwaiti",
        "kyrgyz",
        "laotian",
        "latvian",
        "lebanese",
        "liberian",
        "libyan",
        "liechtensteiner",
        "lithuanian",
        "luxembourger",
        "macedonian",
        "malagasy",
        "malawian",
        "malaysian",
        "maldivan",
        "malian",
        "maltese",
        "marshallese",
        "mauritanian",
        "mauritian",
        "mexican",
        "micronesian",
        "moldovan",
        "monacan",
        "mongolian",
        "moroccan",
        "mosotho",
        "motswana",
        "mozambican",
        "namibian",
        "nauruan",
        "nepalese",
        "new zealander",
        "nicaraguan",
        "nigerian",
        "nigerien",
        "north korean",
        "northern irish",
        "norwegian",
        "omani",
        "pakistani",
        "palauan",
        "panamanian",
        "papua new guinean",
        "paraguayan",
        "peruvian",
        "polish",
        "portuguese",
        "qatari",
        "romanian",
        "russian",
        "rwandan",
        "saint lucian",
        "salvadoran",
        "samoan",
        "san marinese",
        "sao tomean",
        "saudi",
        "scottish",
        "senegalese",
        "serbian",
        "seychellois",
        "sierra leonean",
        "singaporean",
        "slovakian",
        "slovenian",
        "solomon islander",
        "somali",
        "south african",
        "south korean",
        "spanish",
        "sri lankan",
        "sudanese",
        "surinamer",
        "swazi",
        "swedish",
        "swiss",
        "syrian",
        "taiwanese",
        "tajik",
        "tanzanian",
        "thai",
        "togolese",
        "tongan",
        "trinidadian or tobagonian",
        "tunisian",
        "turkish",
        "tuvaluan",
        "ugandan",
        "ukrainian",
        "uruguayan",
        "uzbekistani",
        "venezuelan",
        "vietnamese",
        "welsh",
        "yemenite",
        "zambian",
        "zimbabwean"
    ],
    "civil_status" => [
        "single",
        "married",
        "divorced",
        "widowed"
    ],
    //make roles in an orderly manner (hierarchy), the RoleOrder.php uses this. 
    "roles" => [
        "member",
        "barangay",
        "municipal",
        "provincial",
        "regional",
        "national"
    ],
    "attainments" => [
        "no_response" => "No Response",
        "none" => "None",
        "primary_school" => "Primary School",
        "high_school" => "High School",
        "senior_high_school" => "Senior High School",
        "vocational" => "Vocational School",
        "undergraduate" => "Undergraduate Degree",
        "college_graduate" => "College Graduate",
        "doctorate" => "Doctorate Degree"
    ],
    "rate_limit" => [
        "user_info" => 30,
        "user" => 30
    ]
];
